### ISSUE TITLE
Incorrect name in folder components of styles

### ISSUE THREAD

**Issue by herberthenrique** [lyef/lyef-redux-boilerplate#2]
the folder `components` inside `src/styles`It's written wrong.

**Comment by willianjusten** [comment]
Thanks =)

**Comment by herberthenrique** [comment]
I wanted to open a PR to solve this, but I could not even see it right.
@willianjusten was fast as a flash! Hahaha

Thanks!

**Comment by willianjusten** [comment]
ahuhauhuaa =p
