### ISSUE TITLE
Add css file minified

### ISSUE THREAD

**Issue by renanrboliveira** [lyef/lyef-redux-boilerplate#5]
Hi guys,

What do you think to add css files minified?

**Comment by willianjusten** [comment]
As far as I remember, it was already doing that, including the use of PostCSS, but I'll check about it.

**Comment by renanrboliveira** [comment]
I didn't find, just set snippet below:
Example:
`{
  loader: 'css-loader',
  options: {
    minimize: true || {/* CSSNano Options */}
  }
}`

**Comment by guilouro** [comment]
Hey @renanrboliveira , 
The css is minified when running this command `npm run build` based on [this file](https://github.com/lyef/lyef-redux-boilerplate/blob/master/webpack/prod.js).

**Comment by willianjusten** [comment]
Exactly, with that, I think we can close this issue.
